package com.dayworks_ltd.loyalty_engine.customer_segregation.enums;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum CustomerSegment {
    NEW_CUSTOMER("NEW CUSTOMER"),
    ACTIVE_CUSTOMER("ACTIVE CUSTOMER"),
    LOYAL_CUSTOMER("LOYAL CUSTOMER"),
    DORMANT_CUSTOMER("DORMANT CUSTOMER"),
    CHURNED_CUSTOMER("CHURNED CUSTOMER"),

    LOW_SPENDER("LOW SPENDING CUSTOMER"),
    MEDIUM_SPENDER("MEDIUM SPENDING CUSTOMER"),
    HIGH_SPENDER("HIGH SPENDING CUSTOMER"),
    VIP("VERY HIGH SPENDING CUSTOMER"),

    FREQUENT_BUYER("FREQUENT BUYING CUSTOMER"),
    BULK_BUYER("BULK BUYING CUSTOMER"),
    ONE_TIME_BUYER("ONE TIME BUYING CUSTOMER"),

    RECOVERING_CUSTOMER("RECOVERING CUSTOMER"),
    DECLINING_CUSTOMER("DECLINING CUSTOMER"),
    CONSISTENT_CUSTOMER("CONSISTENT CUSTOMER");

    CustomerSegment(String segment)
    {}
}
